apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:682651395775:certificate/ebeac7f9-8167-4680-9f72-0a23a67eec99"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=dev,app=test"
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: CONTAINER_IMAGE
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080

